### ISSUE TITLE
0.19 Support

### ISSUE THREAD

**Issue by tilmans** [klaftertief/slippery-slope#4]
Thanks for the great library!
Since I'm using it in one of my projects I've created a fork and started porting it to 0.19. Let me know if you are interested in getting a (huge) merge request or if you'd rather do this yourself.

Cheers,
Tilman

**Comment by klaftertief** [comment]
Hi Tilman,
I actually recommend not to use the library at this stage. I had to stop working on it some time ago, decided to rethink some implementations sometime later, started on a private fork and had to stop working on it again.
So to not give users the impression that this library is ready to use I'd rather not have it updated to 0.19.
I hope to find the time to start working on the library again and better communicate and coordinate things, as it kind of hurts to respond like that :-)

**Comment by tilmans** [comment]
Hi, what I'll do then is just integrate it in my own app for now as I migrate that to 0.19. It would be great to see a new release of this library as it has been a joy to use.

Cheers,
Tilman

**Comment by klaftertief** [comment]
That’s nice to year. I know the pain of communicating with a JS slippy map, which motivated me to start with a pure Elm version. 
If you don’t mind very async communication I’m happy to share some ideas...
